M48
; DRILL file {KiCad (6.0.10-0)} date 2023 September 02, Saturday 13:11:51
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-09-02T13:11:51+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X50.8Y-35.56
X50.8Y-105.56
X190.8Y-35.56
X190.8Y-105.56
T0
M30
